### ISSUE TITLE
golang 1.10

### ISSUE THREAD

**Issue by glebteterin** [instrumentisto/dep-docker-image#1]
Hi there,
Is there a chance the image will use golang 1.10 any soon?

**Comment by tyranron** [comment]
@g-rad yup, with a next release.

Does it introduce a problem for your case?

**Comment by glebteterin** [comment]
@tyranron yeah, we are using strings.builder which was introduced in 1.10

**Comment by tyranron** [comment]
@g-rad seems to be reasonable. I've updated the current `master`, so the latest image versions are rebuilt with Go 1.10, and your issue should be resolved now. I hope that won't break any other workloads.
